server:
  service:
    type: ClusterIP
  ingress:
    enabled: false
  metrics:
    enabled: true
controller:
  replicas: 1
  metrics:
    enabled: true
repoServer:
  replicas: 1
  metrics:
    enabled: true
dex:
  enabled: false
configs:
 params:
    server.insecure: "false"
applicationSet:
  metrics:
    enabled: true
