server:
  service:
    type: ClusterIP
  ingress:
    enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

dex:
  enabled: false

redis:
  enabled: true

configs:
  rbac:
    policy.csv: |
      p, role:readonly, applications, get, */*, allow
      g, myteam, role:readonly
    scopes: "[groups]"
